### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by jimmyolo** [log4js-node/smtp#1]
1. miss transport & SMTP is not allowed
```js
"use strict";
const log4js = require("log4js");
log4js.configure({
	appenders: {
		email: {
			type: "@log4js-node/smtp", recipients: "jimmy.huang@concords.com.tw",
			//SMTP: { host: "localhost", port: 25 },
			//transport: { plugin: "smtp", options: { host: "localhost", port: 25 } },
		}
	},
	categories: { default: { appenders: ["email"], level: "ERROR" } }
});

const log = log4js.getLogger();
log.error("test");
log4js.shutdown(console.log);

/*
/home/Projects/MMWarrantsDB/scheduleDB/node_modules/nodemailer/lib/nodemailer.js:32
        (typeof transporter === 'object' && typeof transporter.send !== 'function') ||
                                                               ^

TypeError: Cannot read property 'send' of null
    at Object.module.exports.createTransport (/home/Projects/MMWarrantsDB/scheduleDB/node_modules/nodemailer/lib/nodemailer.js:32:64)
    at smtpAppender (/home/Projects/MMWarrantsDB/scheduleDB/node_modules/@log4js-node/smtp/lib/index.js:40:28)
    at Object.configure (/home/Projects/MMWarrantsDB/scheduleDB/node_modules/@log4js-node/smtp/lib/index.js:135:10)
    at clustering.onlyOnMaster (/home/Projects/MMWarrantsDB/scheduleDB/node_modules/log4js/lib/appenders/index.js:59:27)
    at Object.onlyOnMaster (/home/Projects/MMWarrantsDB/scheduleDB/node_modules/log4js/lib/clustering.js:74:50)
    at createAppender (/home/Projects/MMWarrantsDB/scheduleDB/node_modules/log4js/lib/appenders/index.js:57:21)
    at Object.keys.forEach (/home/Projects/MMWarrantsDB/scheduleDB/node_modules/log4js/lib/appenders/index.js:73:25)
    at Array.forEach (<anonymous>)
    at setup (/home/Projects/MMWarrantsDB/scheduleDB/node_modules/log4js/lib/appenders/index.js:71:33)
    at listeners.forEach.listener (/home/Projects/MMWarrantsDB/scheduleDB/node_modules/log4js/lib/configuration.js:36:33)
*/
```

2. smtp option is case sensitive, example is not correct
```js
log4js.configure({
	appenders: {
		email: {
			type: "@log4js-node/smtp", recipients: "jimmy.huang@concords.com.tw",
			smtp: { host: "localhost", port: 25 },
			//transport: { plugin: "smtp", options: { host: "localhost", port: 25 } },
		}
	},
	categories: { default: { appenders: ["email"], level: "ERROR" } }
});

/* same output with 1.
        (typeof transporter === 'object' && typeof transporter.send !== 'function') ||
                                                               ^
TypeError: Cannot read property 'send' of null
*/
```

3. smtp/transport port default to 587 (since nodemailer `defaults to 587 if is secure is false or 465 if true`)
```js
log4js.configure({
	appenders: {
		email: {
			type: "@log4js-node/smtp", recipients: "jimmy.huang@concords.com.tw",
			SMTP: { },
			//transport: { plugin: "smtp", options: { } },
		}
	},
	categories: { default: { appenders: ["email"], level: "ERROR" } }
});

/*
log4js.smtpAppender - Error happened { Error: connect ECONNREFUSED 127.0.0.1:587
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1162:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNECTION',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 587,
  command: 'CONN' }
*/
```

**Comment by nomiddlename** [comment]
Published to npm in version 1.0.1
